version: "3"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_project_demo}"
    env_file: .env
    image: localstack/localstack:0.10.6
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_SERVICES=${LOCALSTACK_SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    # volumes:
    #   - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
